
// Objective-C API for talking to the following Go packages
//
//	github.com/avikalpg/whatsapp-ai-filter/wabridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Wabridge_FRAMEWORK_H__
#define __Wabridge_FRAMEWORK_H__

#include "Wabridge.objc.h"
#include "Universe.objc.h"

#endif
