// Objective-C API for talking to github.com/avikalpg/whatsapp-ai-filter/wabridge Go package.
//   gobind -lang=objc github.com/avikalpg/whatsapp-ai-filter/wabridge
//
// File is generated by gobind. Do not edit.

#ifndef __Wabridge_H__
#define __Wabridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WabridgeBridge;
@class WabridgeSyncResult;
@protocol WabridgeMessageCallback;
@class WabridgeMessageCallback;

@protocol WabridgeMessageCallback <NSObject>
- (void)onMessage:(NSString* _Nullable)jsonPayload;
@end

/**
 * Bridge is the main object exposed to native code via gomobile.
 */
@interface WabridgeBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBridge creates a new Bridge instance, opening the SQLite database at dbPath.
claudeApiKey is used for AI triage calls.
 */
- (nullable instancetype)init:(NSString* _Nullable)dbPath claudeApiKey:(NSString* _Nullable)claudeApiKey;
/**
 * DeleteFilter removes a filter and all its matches by id.
 */
- (BOOL)deleteFilter:(NSString* _Nullable)id_ error:(NSError* _Nullable* _Nullable)error;
/**
 * GetFilters returns a JSON array of all saved filters.
 */
- (NSString* _Nonnull)getFilters:(NSError* _Nullable* _Nullable)error;
/**
 * GetMatches returns a JSON array of filter matches for the given filterId.
Pass limit=0 for all matches.
 */
- (NSString* _Nonnull)getMatches:(NSString* _Nullable)filterId limit:(long)limit error:(NSError* _Nullable* _Nullable)error;
/**
 * IsLinked returns true if this bridge has a stored WhatsApp session.
 */
- (BOOL)isLinked;
/**
 * SaveFilter creates or updates a filter from a JSON object.
Returns the saved filter as JSON (with id/timestamps populated).
 */
- (NSString* _Nonnull)saveFilter:(NSString* _Nullable)filterJson error:(NSError* _Nullable* _Nullable)error;
/**
 * StartPairing initiates a phone-number pairing flow.
Returns the pairing code that the user must enter in WhatsApp → Linked Devices.
 */
- (NSString* _Nonnull)startPairing:(NSString* _Nullable)phoneNumber error:(NSError* _Nullable* _Nullable)error;
/**
 * SyncAndTriage connects to WhatsApp, collects messages since lastSyncTimestamp,
runs AI triage against all saved filters, and disconnects.
Results are persisted to the local DB; matched messages are also delivered via callback.
 */
- (WabridgeSyncResult* _Nullable)syncAndTriage:(int64_t)lastSyncTimestamp callback:(id<WabridgeMessageCallback> _Nullable)callback error:(NSError* _Nullable* _Nullable)error;
/**
 * Unlink removes the stored WhatsApp session (logout).
 */
- (BOOL)unlink:(NSError* _Nullable* _Nullable)error;
@end

/**
 * SyncResult is returned by SyncAndTriage.
 */
@interface WabridgeSyncResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long messagesSynced;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * NewBridge creates a new Bridge instance, opening the SQLite database at dbPath.
claudeApiKey is used for AI triage calls.
 */
FOUNDATION_EXPORT WabridgeBridge* _Nullable WabridgeNewBridge(NSString* _Nullable dbPath, NSString* _Nullable claudeApiKey, NSError* _Nullable* _Nullable error);

@class WabridgeMessageCallback;

/**
 * MessageCallback is implemented by the native layer to receive messages.
 */
@interface WabridgeMessageCallback : NSObject <goSeqRefInterface, WabridgeMessageCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onMessage:(NSString* _Nullable)jsonPayload;
@end

#endif
